### ISSUE TITLE
Extend terminal sigma mapping

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/greek#15]
Map s + [space, punctuation or final position] to terminal sigma

**Comment by neelsmith** [comment]
currently only doing mapping when sigma is followed by space

**Comment by Eumaeus** [comment]
val uc:String = [Some string with possibly messed up sigmas]
val sigmaTerminators:Vector[String] = Vector(",",".",":", ";", "'", "—", " ", "\t")
val matcher = "σ.".r	
val stringWithFixedSigmas = {
	matcher.replaceAllIn(uc, m => {
		val secondChar:String = m.group(0).tail
		if (sigmaTerminators.contains(secondChar)) { s"ς${secondChar}"}
		else { s"σ${secondChar}"}
	})
}

**Comment by Eumaeus** [comment]
I've been working with this library a bit lately. The above code is what I've implemented on an *ad hoc* basis to sort out sigmas.

**Comment by neelsmith** [comment]
Fixed and tested.
