### ISSUE TITLE
LGSyllable makes an error on ἔστι

### ISSUE THREAD

**Issue by zachsowerby** [neelsmith/greek#37]
Running the following code in `sbt`, in which `urn:cts:greekMusic:seikilos.1.normalized:` contains the word ἔστι:
>val seikilosTextUrn = CtsUrn("urn:cts:greekMusic:seikilos.1.normalized:")
val seikilosTextCorpus = repo.corpus ~~ seikilosTextUrn
val diplomaticText = reader.edition(seikilosTextCorpus)
val seikilosWordsCorpus = LiteraryGreekString.tokenizedCorpus(diplomaticText)
val seikilosTextSyllableCorpus = LGSyllable.tokenizedCorpus(seikilosWordsCorpus)
val seikilosTextSyllables = seikilosTextSyllableCorpus.nodes
seikilosTextSyllables(16)

Garners this result:
>res9: edu.holycross.shot.ohco2.CitableNode = CitableNode(urn:cts:greekMusic:seikilos.1.normalized_dipl_tkns_sylls:3.2.0,ἔστι)

ἔστι here does not seem to be syllabifying properly. Interestingly enough ἐστὶ syllabifies fine.

**Comment by neelsmith** [comment]
LGSyllable is not part of this library.  It's part of the gsphonology library.  Closing this issue, opening one in gsphonology.
